-- Neural Nexus Administrative & Staff Portal
-- Run this in Supabase SQL Editor.
-- Keep SUPABASE_SERVICE_ROLE_KEY only on the server/Vercel environment.

create table if not exists public.staff (
    id bigint generated by default as identity primary key,
    name text not null,
    email text,
    phone text,
    role text default 'Staff',
    status text default 'Active',
    created_at timestamptz default now()
);

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    student_code text,
    name text not null,
    register_no text,
    college text,
    course text,
    department text,
    year text,
    phone text,
    email text,
    address text,
    created_at timestamptz default now()
);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    project_code text,
    title text not null,
    student_id bigint references public.students(id) on delete set null,
    domain text,
    technology text,
    staff_id bigint references public.staff(id) on delete set null,
    priority text default 'Normal',
    status text default 'Enquiry',
    start_date date,
    deadline date,
    amount numeric(12,2) default 0,
    github_url text,
    drive_url text,
    notes text,
    created_at timestamptz default now()
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    project_id bigint references public.projects(id) on delete set null,
    student_id bigint references public.students(id) on delete set null,
    amount numeric(12,2) not null default 0,
    payment_date date default current_date,
    method text default 'UPI',
    transaction_id text,
    notes text,
    created_at timestamptz default now()
);

create index if not exists idx_students_name on public.students(name);
create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_projects_student on public.projects(student_id);
create index if not exists idx_payments_project on public.payments(project_id);
